"""add souvenir flag to variants and prices

Revision ID: 142d74c56ecf
Revises: 2d79c3485c2c
Create Date: 2026-07-06 20:28:05.199494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142d74c56ecf'
down_revision: Union[str, Sequence[str], None] = '2d79c3485c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skin_prices', sa.Column('souvenir', sa.Boolean(), nullable=False))
    op.add_column('skin_variants', sa.Column('souvenir', sa.Boolean(), nullable=False))
    op.add_column('user_skins', sa.Column('souvenir', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skins', 'souvenir')
    op.drop_column('skin_variants', 'souvenir')
    op.drop_column('skin_prices', 'souvenir')
    # ### end Alembic commands ###
