"""add_user_portfolio_snapshots_table

Revision ID: 1f670ca879e8
Revises: 142d74c56ecf
Create Date: 2026-07-07 18:59:23.817105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f670ca879e8'
down_revision: Union[str, Sequence[str], None] = '142d74c56ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('items_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_portfolio_snapshots_created_at'), 'user_portfolio_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_portfolio_snapshots_user_id'), 'user_portfolio_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_portfolio_snapshots_user_id'), table_name='user_portfolio_snapshots')
    op.drop_index(op.f('ix_user_portfolio_snapshots_created_at'), table_name='user_portfolio_snapshots')
    op.drop_table('user_portfolio_snapshots')
    # ### end Alembic commands ###
