"""initial_migration

Revision ID: 210066a4c77b
Revises: 
Create Date: 2026-01-19 16:10:33.588836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210066a4c77b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skin_variants',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('skin_id', sa.UUID(), nullable=False),
    sa.Column('wear_id', sa.UUID(), nullable=False),
    sa.Column('stattrack', sa.Boolean(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('change_1h', sa.Float(), nullable=True),
    sa.Column('change_24h', sa.Float(), nullable=True),
    sa.Column('change_7d', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.skin_id'], ),
    sa.ForeignKeyConstraint(['wear_id'], ['wear_types.wear_id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_index('idx_price_history', 'skin_prices', ['skin_id', 'wear_id', 'stattrack', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_history', table_name='skin_prices')
    op.drop_table('skin_variants')
    # ### end Alembic commands ###
