"""add last_inventory_sync to user

Revision ID: 2d79c3485c2c
Revises: e5ecc8365bc2
Create Date: 2026-07-06 16:15:27.771962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d79c3485c2c'
down_revision: Union[str, Sequence[str], None] = 'e5ecc8365bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_inventory_synced', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_inventory_synced')
    # ### end Alembic commands ###
