"""init_schema_fixed

Revision ID: 3c61a403c18d
Revises: 
Create Date: 2025-12-12 23:23:54.594733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c61a403c18d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins',
    sa.Column('skin_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('float_min', sa.Float(), nullable=False),
    sa.Column('float_max', sa.Float(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('weapon_id', sa.UUID(), nullable=False),
    sa.Column('rarity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarities.rarity_id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.weapon_id'], ),
    sa.PrimaryKeyConstraint('skin_id'),
    sa.UniqueConstraint('name', 'weapon_id', name='uq_skin_weapon')
    )
    op.create_index(op.f('ix_skins_name'), 'skins', ['name'], unique=False)
    op.create_foreign_key(None, 'skin_prices', 'skins', ['skin_id'], ['skin_id'])
    op.create_foreign_key(None, 'user_skins', 'skins', ['skin_id'], ['skin_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_skins', type_='foreignkey')
    op.drop_constraint(None, 'skin_prices', type_='foreignkey')
    op.drop_index(op.f('ix_skins_name'), table_name='skins')
    op.drop_table('skins')
    # ### end Alembic commands ###
