"""add_quantity_to_skin_variants

Revision ID: e5ecc8365bc2
Revises: 210066a4c77b
Create Date: 2026-01-25 19:22:38.340581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ecc8365bc2'
down_revision: Union[str, Sequence[str], None] = '210066a4c77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skin_variants', sa.Column('quantity', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skin_variants', 'quantity')
    # ### end Alembic commands ###
